### ISSUE TITLE
Part3 Discussion

### ISSUE THREAD

**Issue by Magicboy-Zhang** [CMPUT301W22T01/QRpokemon#43]
Used to chat in the period of Part 3

**Comment by Magicboy-Zhang** [comment]
Seems like xml in branch "other_user_interface_Activity" and "qr_interface" are the same, prefer "other_user_interface_Activity"

**Comment by Magicboy-Zhang** [comment]
Have already tested how to integrate Google Maps into our application with @xiaolvgao

**Comment by MayoDuckPy** [comment]
We're using Google Maps? Not OpenStreetMaps?

**Comment by Magicboy-Zhang** [comment]
> We're using Google Maps? Not OpenStreetMaps?

Google map might be better if we can actually use it, but will ask for TA or other's advice.
