### ISSUE TITLE
Use RecyclerView for Leaderboard and Inventory

### ISSUE THREAD

**Issue by MayoDuckPy** [CMPUT301W22T01/QRpokemon#62]
We should switch the current ListView implementations in favour of RecyclerViews which display large datasets far more efficiently.

**Comment by MayoDuckPy** [comment]
Commit f2d026b in branch `leaderboard_Activity` adds a RecyclerView to the leaderboard.

We should focus on adding a RecyclerView to the Inventory page now.

**Comment by Yutong13** [comment]
Recycler view is used for OwnerActivity as well
