### ISSUE TITLE
Organize code into different directories

### ISSUE THREAD

**Issue by MayoDuckPy** [CMPUT301W22T01/QRpokemon#63]
As discussed during our demo, we should organize our code into various directories.

Since Activities typically require Adapters and more, it may be a good idea to **organize most of our code based on the Activity** (Activity-related objects and their Controllers) that relates to it. However, the **MainActivity should stay as it is** since it's the entry-point to our app. It also would be best to **group models into their own directory**.

**Comment by MayoDuckPy** [comment]
I have added a directory for activities in commit 8838cae with the current leaderboard implementation residing there. Hopefully that adds clarification on the structure.

**Comment by Yutong13** [comment]
qrscanned and qrinventory classes has been put into directories, will do the rest soon.

**Comment by Yutong13** [comment]
Done.
