### ISSUE TITLE
Admin users need to implement

### ISSUE THREAD

**Issue by Yutong13** [CMPUT301W22T01/QRpokemon#69]
We can either give user a password field for admin user to log in.
Or we can have admin device set up in advanced on Firestore.

**Comment by MayoDuckPy** [comment]
Owner is defined as **Owner: the entity that owns the infrastructure that the game runs on.**

~~Since the owner should have access to our database (Firestore), an admin user may not be needed.~~

**Comment by MayoDuckPy** [comment]
Implemented by @Yutong13 in commit 9cc9706
