### ISSUE TITLE
Refactor `getPlayer()` in PlayerController

### ISSUE THREAD

**Issue by MayoDuckPy** [CMPUT301W22T01/QRpokemon#74]
Currently, the `getPlayer()` method in PlayerController allows us to fetch a single player and multiple players. To improve code quality, this method should be separated into methods which fetch a single player and another which fetches multiple. Additionally, the latter method should allow us to pass the sortField parameter used in `DatabaseController.getData()` so that player data is returned in sorted order.

**Comment by Yutong13** [comment]
It's done, I created getAllPlayers() method in PlayerController class
