### ISSUE TITLE
Final testing of all the user stroies 

### ISSUE THREAD

**Issue by Magicboy-Zhang** [CMPUT301W22T01/QRpokemon#80]
Now start testing all User Stories, will report success or problems here.

**Comment by Magicboy-Zhang** [comment]
[2022.4.3] 14:31

US 01.01.01
As a player, I want to add new QR codes to my account.

- [x] 1. Scanning when there's no code in the inventory 
- [x] 2. Scanning when there's one code in the inventory
- [x] 3. Scanning when there are many codes (> 2) in the inventory
- [x] 4. Scanning a code and then scanning it again
- [x] 5. Scanning a code, then delete it by clicking the delete button and scan it again
- [x] 6. Scanning a code, then delete it by logging in as an administrator and scanning it again
- [ ] 7. Scanning 2 codes, then delete one of them by logging in as an administrator and scanning it again

**Comment by Magicboy-Zhang** [comment]
US 01.01.01 Bug found
- [x] 7 Fixed

**Comment by Magicboy-Zhang** [comment]
US 01.02.01

As a player, I want to see what QR codes I have added to my account.

- [x] 1. Add a few QR codes into the inventory and check if those codes match the QR codes in the firebase
- [x] 2. Delete a QR code by clicking the delete button and check if those codes match the QR codes in the firebase
- [x] 3. Delete a QR code by logging in as an administrator and check if those codes match the QR codes in the firebase

**Comment by Yutong13** [comment]
> US 01.01.01 Bug found
> 
> * [x]  7 Fixed

This is fixed in QrScannedActivity

**Comment by Magicboy-Zhang** [comment]
US 01.03.01

As a player, I want to remove QR codes from my account.

- [x] 1. Remove a code from inventory and check if the rest QR codes match the QR codes in the firebase 
    - [x] higestUnique is updated
    - [x] qrCount is updated
    - [x] qrInventory is updated
    - [x] totalScore is updated

**Comment by Magicboy-Zhang** [comment]
US 01.04.01

As a player, I want to see my highest and lowest scoring QR codes.

- [x] 1. Clicking the 'ascending' button will set the QR inventory to ascending order
- [x] 2. Clicking the 'descending' button will set the QR inventory to descending order
- [x] 3. Delete any one of the codes and check if the buttons also work

**Comment by Magicboy-Zhang** [comment]
US 01.05.01

As a player, I want to see the sum of scores of QR codes that I have scanned.

- [x] 1. Check if the sum of the score of QR codes matches the real score
- [x] 2. Delete a QR code by clicking the delete button and check if the sum of the score of QR codes matches the real score
- [x] 3. Delete a QR code by logging in as an administrator and check if the sum of the scores of QR codes matches the real score
- [x] 4. Add a QR code and check if the sum of the scores of QR codes matches the real score

**Comment by Magicboy-Zhang** [comment]
US 01.06.01

As a player, I want to see the total number of QR codes that I have scanned.

- [x] 1. Check if the total number of QR codes matches the real number
- [x] 2. Delete a QR code by clicking the delete button and checking if the total number of QR codes matches the real number
- [x] 3. Delete a QR code by logging in as an administrator and check if the total number of QR codes matches the real number
- [x] 4. Add a QR code and check if the total number of QR codes matches the real number

**Comment by Magicboy-Zhang** [comment]
US 01.07.01

As a player, I want to see other player’s profiles

- [x] 1. Search for some keywords and check to see if the profiles of all relevant players are correctly displayed
    - [x] Identifier correctly displayed
    - [x] Email correctly displayed
    - [x] Phone number correctly displayed

**Comment by Magicboy-Zhang** [comment]
US 02.01.01

As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object.

- [x] 1. Enable 'Save QR' only, check if the QR code is correctly recorded without saving location
- [x] 2. Enable 'Save Location' only, check if the QR code is correctly recorded without saving the photo
- [x] 3. Enable both 'Save Location' and 'Save QR', check if the QR code is correctly recorded with both location and photo
- [x] 4. Do not enable 'Save Location' and 'Save QR', check if the QR code is correctly recorded without location and photo

**Comment by Magicboy-Zhang** [comment]
US 02.02.01

As a player, I want to be able to comment on QR codes.

- [x] 1. Comment one of the code from the current player, check if the comment is correctly displayed and added into firebase

**Comment by Magicboy-Zhang** [comment]
US 02.03.01

As a player, I want to be able to browse QR codes that other players have scanned.

- [x] 1. Scan a QR code that represents the inventory of a player, that inventory should be the same as it should be.
    - [x] Inventory content should be correctly displayed
    - [x] the sum of scores should be correctly displayed 
    - [x] the total number should be correctly displayed 
    - [x] players can only see the comments of any one of those codes, that is, is not able to delete or add comments

- [x] 2. Let that player add a code, then check if the data is updated

**Comment by Magicboy-Zhang** [comment]
Bug found, fix a bug that the app crashes when browsing other player's inventory

- [x] Fixed

**Comment by Magicboy-Zhang** [comment]
US 02.04.01

As a player, I want to see that other players have scanned the same QR code.

- [x] 1. Check if the Qr codes scanned by many people will prompt a message that tells the player that it is not unique to him/herself

**Comment by Magicboy-Zhang** [comment]
US 03.01.01

As a player, I want to be able to generate QR codes so that other players can scan my QR code to see my game status.

- [x] same as US 02.03.01 / 01.07.01

**Comment by Magicboy-Zhang** [comment]
US 03.02.01

As a player, I want to be able to generate a QR code so that I can log in to another device with the same account. 

- [x] 1.Generate a code for the current player and log in using another device, check if everything is the same as it was the last time player logged in
    - [x] QR inventory is running smoothly
    - [x] leaderboard is running smoothly
    - [x] map is running smoothly
    - [x] search is running smoothly
    - [x] profile is running smoothly
    - [x] scanning new QR code is running smoothly

**Comment by Magicboy-Zhang** [comment]
US 04.01.01

As a player, I want a profile with a unique username and my contact information.

- [x] 1.  check if all the information matches the data on firebase
    - [x] username displayed correctly
    - [x] phone number displayed correctly
    - [x] email displayed correctly

**Comment by Magicboy-Zhang** [comment]
US 04.02.01 

As a player, I do not want to log into my application using a username and password as my device can identify me.

- [x] 1. Automatically log in

**Comment by Magicboy-Zhang** [comment]
US 05.01.01

As a player, I want to search for other players by username.

- [x] 1. Enter something in the search box, then check if all the players that the keyword is a part of their identifier are correctly displayed
- [x] 2. Delete a player and check the same thing

**Comment by Magicboy-Zhang** [comment]
US 05.02.01

As a player, I want to search for nearby QR codes by using geolocation.

- [x] 1. Enter something in the search box,  then check if all the locations that the keyword is a part of its identifier are correctly displayed
- [x] 2. Delete a location and check the same thing

**Comment by Magicboy-Zhang** [comment]
US 06.01.01

As a player, I want to see a map of geo-locations of nearby QR codes.

- [x] 1. Check if the map works fine
    - [x] automatic positioning
    - [x] display all QR codes

**Comment by Magicboy-Zhang** [comment]
US 07.01.01

As a player, I want to see game-wide high scores of all players.

- [x] 1. Check if the  data in the current leaderboard matches the firebase
- [x] 2. Delete one of the codes by clicking the delete button and check if the data in the current leaderboard matches the firebase
- [x] 3. Delete one of the codes by  logging in as an administrator and check if the data in the current leaderboard matches the firebase
- [x] 4. Add a QR code and check if the data in the current leaderboard matches the firebase
- [x] 5. After changing device, check all things above

**Comment by Magicboy-Zhang** [comment]
US 07.02.01

As a player, I want an estimate of my ranking for the highest scoring unique QR code.

- [x] 1. Check if my ranking for the highest scoring unique QR code is correctly displayed
- [x] 2. Delete one of the codes(two ways) from my inventory that will lead my ranking to decrease, then check if my ranking for the highest scoring unique QR code is correctly displayed

**Comment by Magicboy-Zhang** [comment]
US 07.03.01

As a player, I want an estimate of my ranking for the total number of QR codes scanned.

 - [x] 1. Check if my ranking for the total number of QR codes scanned is correctly displayed
 - [x] 2. Delete one of the codes(two ways) from my inventory that will lead my ranking to decrease, then check if my ranking for the total number of QR codes scanned is correctly displayed

**Comment by Magicboy-Zhang** [comment]
US 07.04.01

As a player, I want an estimate of my ranking for a total sum of scores of QR codes scanned.

- [x] 1. Check if my ranking for a total sum of scores of QR codes scanned is correctly displayed
- [x] 2. Delete one of the codes(two ways) from my inventory that will lead my ranking to decrease, then check if my ranking for a total sum of scores of QR codes scanned is correctly displayed

**Comment by Magicboy-Zhang** [comment]
US 08.01.01

As a player, I don’t want the actual code recorded. E.g., so I can scan and score my vaccine passport.

- [x] 1. Has an option when successfully scanning a QR code that let the player choose if he or she wants to save the photo

**Comment by Magicboy-Zhang** [comment]
US 08.02.01

As a player, I want to be able to decline recording geolocation for privacy reasons.

- [x] 1. Has an option when successfully scanning a QR code that let the player choose if he or she wants to save the current location

**Comment by Magicboy-Zhang** [comment]
US 09.01.01 

As an owner, I don’t want to store big images online.

- [x] 1. Save the bitmap of images instead of saving the real images

**Comment by Magicboy-Zhang** [comment]
US 09.02.01 

As an owner, I want to be able to delete QR codes that are bad or malicious.

- [x] 1. Check if a user can log in as an owner
- [x] 2. After logging in as the owner, check if the current player is able to delete any one of the QR codes 
- [x] 3. After deleting the QR code, that code should be deleted from all the inventory that originally contains that code

**Comment by Magicboy-Zhang** [comment]
US 09.03.01 

As an owner, I want to be able to delete players.

- [x] 1. After logging in as the owner, check if the current player is able to delete any one of the players 
- [x] 2. After deleting a player, that player should be deleted from firebase
