### ISSUE TITLE
Design UI and Create Storyboards

### ISSUE THREAD

**Issue by MayoDuckPy** [CMPUT301W22T01/QRpokemon#9]
Discussions on the app's UI design and their subsequent storyboards should take place here. Commit all changes to branch `ui-storyboard`.

**Comment by MayoDuckPy** [comment]
UI interface designs have been committed.

**Comment by MayoDuckPy** [comment]
<img src="https://user-images.githubusercontent.com/40531692/152708383-f7869985-4563-42a9-84a4-989f43919685.png" height=500>

We should consider [plantuml](plantuml.com) for creating the storyboards. We'll need to add a border to the svg template if we go this route.

**Comment by MayoDuckPy** [comment]
Just pushed a diagram that documents the start screen to the main menu (193736f).

<img src="https://github.com/CMPUT301W22T01/QRpokemon/blob/ui-storyboard/doc/storyboard/activityDiagram.png?raw=true" height="1000">

**Comment by shangyingl** [comment]
The storyboard for QR inventory
![flowchart](https://user-images.githubusercontent.com/97411729/152852170-f63b4d96-c20b-41bf-8946-792137f4c4fe.jpg)
![QR inventory scroll down](https://user-images.githubusercontent.com/97411729/152852185-b251b3a7-b67c-4c38-bdc3-409a29e250c2.svg)
![QR inventory delete](https://user-images.githubusercontent.com/97411729/152852196-b62fa68d-c495-4468-a32c-a8043a30bc5f.svg)

**Comment by shangyingl** [comment]
storyboard for QR inventory 
<img src="https://user-images.githubusercontent.com/97411729/152852591-fed4cb0b-2851-4b01-9d5f-e9871c49267f.jpg" height="600">
<img src="https://user-images.githubusercontent.com/97411729/152852658-b77ea4e5-9ce6-453b-be83-5c4bb447a923.svg" height="600">
<img src="https://user-images.githubusercontent.com/97411729/152852737-5b2c25de-164f-4685-9f79-3480fc30678d.svg" height="600">

**Comment by xiaolvgao** [comment]
<img src= "https://user-images.githubusercontent.com/50682908/152852943-bb2caeef-06c7-4469-9c0a-718fa4dd0eaa.jpg" height="600">

**Comment by xinran11** [comment]
![image](https://user-images.githubusercontent.com/97500457/152863966-2f77f039-7540-4dd0-85cc-2beff1fc32c0.png)

**Comment by Magicboy-Zhang** [comment]
[Rank.pdf](https://github.com/CMPUT301W22T01/QRpokemon/files/8017990/Rank.pdf)

**Comment by Magicboy-Zhang** [comment]
![Rank_Flow](<img src="https://user-images.githubusercontent.com/74690677/152855889-4d5fe425-95af-4ca6-a07b-4a9b609e058f.png")

**Comment by Magicboy-Zhang** [comment]
![Rank_Flow](https://user-images.githubusercontent.com/74690677/152856097-5b3e88c6-d093-4054-8fbf-f5ec961c7e38.png)

**Comment by Magicboy-Zhang** [comment]
![jb](https://user-images.githubusercontent.com/74690677/152859398-a56c7f85-5cf7-45d8-b628-e12611cefd32.png)

**Comment by Magicboy-Zhang** [comment]
![new_rank](https://user-images.githubusercontent.com/74690677/152859636-4a1d9f38-d54f-403e-8224-ff5ef7d25dbb.png)

**Comment by Magicboy-Zhang** [comment]
Can't figure out the difference between "game-wide high scores of all players" and "estimate of my ranking for a total sum of scores of QR codes scanned".

**Comment by Yutong13** [comment]
User story for search
<img src="https://user-images.githubusercontent.com/78041570/152862307-c1b555df-c34e-4003-af3f-f18c06ae18b3.png" height="500">

**Comment by MayoDuckPy** [comment]
> Can't figure out the difference between "game-wide high scores of all players" and "estimate of my ranking for a total sum of scores of QR codes scanned".

We'll just have to treat them as different unless otherwise noted.

**Comment by Yutong13** [comment]
Missing story points and risk level, will have to discuss with TA for further details.

**Comment by xiaolvgao** [comment]
<img src= "https://user-images.githubusercontent.com/50682908/152863257-2ab14899-93a1-42d5-bb31-e02dba61d8bf.jpeg"height="1000">

**Comment by xiaolvgao** [comment]
<img src= "https://user-images.githubusercontent.com/50682908/152863257-2ab14899-93a1-42d5-bb31-e02dba61d8bf.jpeg" height="600">

**Comment by xinran11** [comment]
![image](https://user-images.githubusercontent.com/97500457/153073687-2cfe7c2f-29eb-427c-ae01-fd098384cb63.png)

**Comment by MayoDuckPy** [comment]
Marking this issue closed due to merging of PR #40. Please create a new issue when the ui/storyboard requires further attention.
